spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5433/mecanosfera_db?options=-c%20timezone=UTC
spring.datasource.username=mecanosfera
spring.datasource.password=mecanosfera123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

jwt.secret=Mk8jsHhd2uRxiab0R06sk11BP3a8lBxqTu+pZpNbtmQ1uMhkk7bQtOeMM8eQ3BC2
jwt.expiration-ms=43200000